from . import res_company
from . import res_partner
from . import pos_order
from . import pos_order_line
from . import ir_ui_view
from . import pos_config
from . import pos_session
from . import account_move
from . import account_move_line
